name: "Bypasses"
description: "Report a bypass"
title: "Bypass with ... for ..."
labels: ["bypass"]
assignees:
- Elikill58
body:
- type: markdown
  attributes:
    value: "Use this template if a cheat isn't detected by Negativity."
- type: dropdown
  id: platform
  attributes:
    label: "Which platform are you using ?"
    multiple: true
    options:
    - Spigot
    - Paper
    - Sponge 7
    - Sponge 8
    - Bungeecord
    - Velocity
    - Other
- type: textarea
  id: versions
  attributes:
    label: "Versions of Negativity and of the server"
    description: "Show output result of `/n debug` command"
    placeholder: "Negativity v1.0, paper v1_8_R3"
    value: "My version is: "
  validations:
    required: true
- type: textarea
  id: describe
  attributes:
    label: "What were you doing while finding bypass ?"
    description: "Please, try to explain (and show with video or screenshoot) to reproduce the bypass."
    placeholder: "Explain the bypass here !"
  validations:
    required: true
- type: textarea
  id: client-mode
  attributes:
    label: "Which client with which mode ?"
    description: "Precise all informations about which cheat exactly: the client (LiquidBounce, Rise, Vape ...), the mode (NPC, vanilla ...)"
    placeholder: "Vape, NPC"
  validations:
    required: true

